--------------------------------------------------------
--  DDL for Sequence AUCTION_BOOK_ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."AUCTION_BOOK_ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence AUCTION_BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."AUCTION_BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."BID_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 30 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CART_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."CART_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDER_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."ORDER_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TEMP_ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."TEMP_ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USED_BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SS230205"."USED_BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 30 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUCTION_BOOK
--------------------------------------------------------

  CREATE TABLE "SS230205"."AUCTION_BOOK" 
   (	"AUCTION_BOOK_ID" NUMBER, 
	"START_PRICE" NUMBER, 
	"STATUS" NUMBER, 
	"BOOK_ID" NUMBER, 
	"SHIPPING_COMPANY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT DELETE ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT INDEX ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT INSERT ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT SELECT ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT READ ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."AUCTION_BOOK" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table AUCTION_BOOK_ORDER
--------------------------------------------------------

  CREATE TABLE "SS230205"."AUCTION_BOOK_ORDER" 
   (	"AUCTION_ORDER_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"AUCTION_BOOK_ID" NUMBER, 
	"BID_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT DELETE ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT INDEX ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT INSERT ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT SELECT ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT READ ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."AUCTION_BOOK_ORDER" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table BIDS
--------------------------------------------------------

  CREATE TABLE "SS230205"."BIDS" 
   (	"BID_ID" NUMBER, 
	"AUCTION_BOOK_ID" NUMBER, 
	"BIDDER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."BIDS" TO PUBLIC;
  GRANT DELETE ON "SS230205"."BIDS" TO PUBLIC;
  GRANT INDEX ON "SS230205"."BIDS" TO PUBLIC;
  GRANT INSERT ON "SS230205"."BIDS" TO PUBLIC;
  GRANT SELECT ON "SS230205"."BIDS" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."BIDS" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."BIDS" TO PUBLIC;
  GRANT READ ON "SS230205"."BIDS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."BIDS" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."BIDS" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."BIDS" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."BIDS" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "SS230205"."BOOK" 
   (	"BOOK_ID" NUMBER, 
	"ISBN" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTHOR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOK_TYPE" NUMBER, 
	"PRICE" NUMBER, 
	"IMAGE_URL" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PUBLISHER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PUB_DATE" DATE, 
	"SELLER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."BOOK" TO PUBLIC;
  GRANT DELETE ON "SS230205"."BOOK" TO PUBLIC;
  GRANT INDEX ON "SS230205"."BOOK" TO PUBLIC;
  GRANT INSERT ON "SS230205"."BOOK" TO PUBLIC;
  GRANT SELECT ON "SS230205"."BOOK" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."BOOK" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."BOOK" TO PUBLIC;
  GRANT READ ON "SS230205"."BOOK" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."BOOK" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."BOOK" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."BOOK" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."BOOK" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SS230205"."CART" 
   (	"CART_ID" NUMBER, 
	"CLIENT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT DELETE ON "SS230205"."CART" TO PUBLIC;
  GRANT INDEX ON "SS230205"."CART" TO PUBLIC;
  GRANT INSERT ON "SS230205"."CART" TO PUBLIC;
  GRANT SELECT ON "SS230205"."CART" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."CART" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."CART" TO PUBLIC;
  GRANT READ ON "SS230205"."CART" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."CART" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."CART" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."CART" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."CART" TO PUBLIC;
  GRANT ALTER ON "SS230205"."CART" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table CART_ITEM
--------------------------------------------------------

  CREATE TABLE "SS230205"."CART_ITEM" 
   (	"CART_ITEM_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"CART_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT DELETE ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT INDEX ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT INSERT ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT SELECT ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT READ ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."CART_ITEM" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."CART_ITEM" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "SS230205"."CLIENTS" 
   (	"CLIENT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS2" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT DELETE ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT INDEX ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT INSERT ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT SELECT ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT READ ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."CLIENTS" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."CLIENTS" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table ORDER_ITEM
--------------------------------------------------------

  CREATE TABLE "SS230205"."ORDER_ITEM" 
   (	"ORDER_ITEM_ID" NUMBER(*,0), 
	"ORDER_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"BOOK_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "SS230205"."REVIEW" 
   (	"REVIEW_ID" NUMBER, 
	"CLIENT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOK_ID" NUMBER, 
	"TITLE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENTS" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATE_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT DELETE ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT INDEX ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT INSERT ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT SELECT ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT READ ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."REVIEW" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."REVIEW" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table TEMP_ORDER
--------------------------------------------------------

  CREATE TABLE "SS230205"."TEMP_ORDER" 
   (	"TEMP_ORDER_ID" NUMBER, 
	"AUCTION_BOOK_ID" NUMBER, 
	"BID_ID" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOK_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT DELETE ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT INDEX ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT INSERT ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT SELECT ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT READ ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."TEMP_ORDER" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."TEMP_ORDER" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table USED_BOOK
--------------------------------------------------------

  CREATE TABLE "SS230205"."USED_BOOK" 
   (	"USED_BOOK_ID" NUMBER, 
	"STATUS" NUMBER, 
	"BOOK_ID" NUMBER, 
	"SHIPPING_COMPANY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT DELETE ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT INDEX ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT INSERT ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT SELECT ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT UPDATE ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT REFERENCES ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT READ ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT QUERY REWRITE ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT DEBUG ON "SS230205"."USED_BOOK" TO PUBLIC;
  GRANT FLASHBACK ON "SS230205"."USED_BOOK" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table orders
--------------------------------------------------------

  CREATE TABLE "SS230205"."orders" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS2" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SHIP_MESSAGE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER, 
	"CLIENT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CARD" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOK_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
REM INSERTING into SS230205.AUCTION_BOOK
SET DEFINE OFF;
Insert into SS230205.AUCTION_BOOK (AUCTION_BOOK_ID,START_PRICE,STATUS,BOOK_ID,SHIPPING_COMPANY) values (4,6800,0,10,'company1');
REM INSERTING into SS230205.AUCTION_BOOK_ORDER
SET DEFINE OFF;
REM INSERTING into SS230205.BIDS
SET DEFINE OFF;
REM INSERTING into SS230205.BOOK
SET DEFINE OFF;
REM INSERTING into SS230205.CART
SET DEFINE OFF;
REM INSERTING into SS230205.CART_ITEM
SET DEFINE OFF;
REM INSERTING into SS230205.CLIENTS
SET DEFINE OFF;
Insert into SS230205.CLIENTS (CLIENT_ID,PASSWORD,NAME,EMAIL,PHONE_NUMBER,ZIPCODE,ADDRESS1,ADDRESS2) values ('kenny','123456789','박케니','keny@gmail.com','01029384','12345','어쩌구','저쩌구');
Insert into SS230205.CLIENTS (CLIENT_ID,PASSWORD,NAME,EMAIL,PHONE_NUMBER,ZIPCODE,ADDRESS1,ADDRESS2) values ('test_man','test','테스트맨','test@test.com','01012345678','02748','서울 성북구 화랑로13길 60','동덕여자대학교');
Insert into SS230205.CLIENTS (CLIENT_ID,PASSWORD,NAME,EMAIL,PHONE_NUMBER,ZIPCODE,ADDRESS1,ADDRESS2) values ('chaney11','123456789','Seo Chaeyeon','chaney11@naver.com','01085054189','05623','29,Songpa-daero 48-gil, Songpa-gu','hosu-imgwang Building ');
REM INSERTING into SS230205.ORDER_ITEM
SET DEFINE OFF;
REM INSERTING into SS230205.REVIEW
SET DEFINE OFF;
REM INSERTING into SS230205.TEMP_ORDER
SET DEFINE OFF;
REM INSERTING into SS230205.USED_BOOK
SET DEFINE OFF;
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (10,0,11,'company2');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (12,0,13,'company1');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (11,0,12,'company1');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (1,0,1,'cj');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (2,0,2,'cj');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (3,0,3,'cj');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (4,0,4,'cj');
Insert into SS230205.USED_BOOK (USED_BOOK_ID,STATUS,BOOK_ID,SHIPPING_COMPANY) values (5,0,5,'cj');
REM INSERTING into SS230205."orders"
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index XPKAUCTIONBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKAUCTIONBOOK" ON "SS230205"."AUCTION_BOOK" ("AUCTION_BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKAUCTIONBOOKORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKAUCTIONBOOKORDER" ON "SS230205"."AUCTION_BOOK_ORDER" ("AUCTION_ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKBIDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKBIDS" ON "SS230205"."BIDS" ("BID_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKBOOK" ON "SS230205"."BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCART
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCART" ON "SS230205"."CART" ("CART_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCARTITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCARTITEM" ON "SS230205"."CART_ITEM" ("CART_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCLIENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCLIENTS" ON "SS230205"."CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKORDER" ON "SS230205"."orders" ("ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORDERITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKORDERITEM" ON "SS230205"."ORDER_ITEM" ("ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKREVIEW" ON "SS230205"."REVIEW" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKTEMPORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKTEMPORDER" ON "SS230205"."TEMP_ORDER" ("TEMP_ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKUSEDBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKUSEDBOOK" ON "SS230205"."USED_BOOK" ("USED_BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKAUCTIONBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKAUCTIONBOOK" ON "SS230205"."AUCTION_BOOK" ("AUCTION_BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKAUCTIONBOOKORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKAUCTIONBOOKORDER" ON "SS230205"."AUCTION_BOOK_ORDER" ("AUCTION_ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKBIDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKBIDS" ON "SS230205"."BIDS" ("BID_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKBOOK" ON "SS230205"."BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCART
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCART" ON "SS230205"."CART" ("CART_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCARTITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCARTITEM" ON "SS230205"."CART_ITEM" ("CART_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCLIENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKCLIENTS" ON "SS230205"."CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORDERITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKORDERITEM" ON "SS230205"."ORDER_ITEM" ("ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKREVIEW" ON "SS230205"."REVIEW" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKTEMPORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKTEMPORDER" ON "SS230205"."TEMP_ORDER" ("TEMP_ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKUSEDBOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKUSEDBOOK" ON "SS230205"."USED_BOOK" ("USED_BOOK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SS230205"."XPKORDER" ON "SS230205"."orders" ("ORDER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AUCTION_BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."AUCTION_BOOK" MODIFY ("AUCTION_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK" ADD CONSTRAINT "XPKAUCTIONBOOK" PRIMARY KEY ("AUCTION_BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUCTION_BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" MODIFY ("AUCTION_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" MODIFY ("AUCTION_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" MODIFY ("BID_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" ADD CONSTRAINT "XPKAUCTIONBOOKORDER" PRIMARY KEY ("AUCTION_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BIDS
--------------------------------------------------------

  ALTER TABLE "SS230205"."BIDS" MODIFY ("BID_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BIDS" MODIFY ("AUCTION_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BIDS" MODIFY ("BIDDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BIDS" ADD CONSTRAINT "XPKBIDS" PRIMARY KEY ("BID_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BOOK" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BOOK" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BOOK" MODIFY ("BOOK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."BOOK" ADD CONSTRAINT "XPKBOOK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SS230205"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CART" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CART" ADD CONSTRAINT "XPKCART" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART_ITEM
--------------------------------------------------------

  ALTER TABLE "SS230205"."CART_ITEM" MODIFY ("CART_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CART_ITEM" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CART_ITEM" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CART_ITEM" ADD CONSTRAINT "XPKCARTITEM" PRIMARY KEY ("CART_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" MODIFY ("ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."CLIENTS" ADD CONSTRAINT "XPKCLIENTS" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "SS230205"."ORDER_ITEM" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."ORDER_ITEM" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."ORDER_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."ORDER_ITEM" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."ORDER_ITEM" ADD CONSTRAINT "XPKORDERITEM" PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SS230205"."REVIEW" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."REVIEW" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."REVIEW" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."REVIEW" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."REVIEW" ADD CONSTRAINT "XPKREVIEW" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMP_ORDER
--------------------------------------------------------

  ALTER TABLE "SS230205"."TEMP_ORDER" MODIFY ("TEMP_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."TEMP_ORDER" MODIFY ("AUCTION_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."TEMP_ORDER" MODIFY ("BID_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."TEMP_ORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."TEMP_ORDER" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."TEMP_ORDER" ADD CONSTRAINT "XPKTEMPORDER" PRIMARY KEY ("TEMP_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USED_BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."USED_BOOK" MODIFY ("USED_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."USED_BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."USED_BOOK" ADD CONSTRAINT "XPKUSEDBOOK" PRIMARY KEY ("USED_BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table orders
--------------------------------------------------------

  ALTER TABLE "SS230205"."orders" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SS230205"."orders" ADD CONSTRAINT "XPKORDER" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUCTION_BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."AUCTION_BOOK" ADD CONSTRAINT "R_28" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUCTION_BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" ADD CONSTRAINT "R_50" FOREIGN KEY ("AUCTION_BOOK_ID")
	  REFERENCES "SS230205"."AUCTION_BOOK" ("AUCTION_BOOK_ID") ENABLE;
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" ADD CONSTRAINT "R_55" FOREIGN KEY ("BID_ID")
	  REFERENCES "SS230205"."BIDS" ("BID_ID") ENABLE;
  ALTER TABLE "SS230205"."AUCTION_BOOK_ORDER" ADD CONSTRAINT "R_41" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SS230205"."orders" ("ORDER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BIDS
--------------------------------------------------------

  ALTER TABLE "SS230205"."BIDS" ADD CONSTRAINT "R_33" FOREIGN KEY ("AUCTION_BOOK_ID")
	  REFERENCES "SS230205"."AUCTION_BOOK" ("AUCTION_BOOK_ID") ENABLE;
  ALTER TABLE "SS230205"."BIDS" ADD CONSTRAINT "R_34" FOREIGN KEY ("BIDDER_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."BOOK" ADD CONSTRAINT "SELLERID" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SS230205"."CART" ADD CONSTRAINT "R_37" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART_ITEM
--------------------------------------------------------

  ALTER TABLE "SS230205"."CART_ITEM" ADD CONSTRAINT "R_31" FOREIGN KEY ("CART_ID")
	  REFERENCES "SS230205"."CART" ("CART_ID") ENABLE;
  ALTER TABLE "SS230205"."CART_ITEM" ADD CONSTRAINT "R_32" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "SS230205"."ORDER_ITEM" ADD CONSTRAINT "R_20" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SS230205"."orders" ("ORDER_ID") ENABLE;
  ALTER TABLE "SS230205"."ORDER_ITEM" ADD CONSTRAINT "R_43" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SS230205"."REVIEW" ADD CONSTRAINT "R_35" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SS230205"."REVIEW" ADD CONSTRAINT "R_51" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMP_ORDER
--------------------------------------------------------

  ALTER TABLE "SS230205"."TEMP_ORDER" ADD CONSTRAINT "FK_TEMPORDER_AUCTIONBOOK" FOREIGN KEY ("AUCTION_BOOK_ID")
	  REFERENCES "SS230205"."AUCTION_BOOK" ("AUCTION_BOOK_ID") ENABLE;
  ALTER TABLE "SS230205"."TEMP_ORDER" ADD CONSTRAINT "FK_TEMPORDER_BID" FOREIGN KEY ("BID_ID")
	  REFERENCES "SS230205"."BIDS" ("BID_ID") ENABLE;
  ALTER TABLE "SS230205"."TEMP_ORDER" ADD CONSTRAINT "FK_TEMPORDER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
  ALTER TABLE "SS230205"."TEMP_ORDER" ADD CONSTRAINT "FK_TEMPORDER_BOOK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USED_BOOK
--------------------------------------------------------

  ALTER TABLE "SS230205"."USED_BOOK" ADD CONSTRAINT "R_29" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SS230205"."BOOK" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table orders
--------------------------------------------------------

  ALTER TABLE "SS230205"."orders" ADD CONSTRAINT "R_53" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "SS230205"."CLIENTS" ("CLIENT_ID") ENABLE;
