spring:
  jpa:
    defer-datasource-initialization : 'true'
    show-sql : 'true'
  datasource:         # Oracle dataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dblab_high?TNS_ADMIN=C:/Oracle/Wallet_DBLab    # use Oracle Wallet
    username: ss230205
    password: Spring_100259
    hikari:          # HikariCP settings
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 2000000
      poolName: HikariPool
  profiles:
    active: test
  devtools:
    livereload:
      enabled: 'true'
  mvc:
   interceptor:
    include: /**
  messages:
    basename: validation


logging:
  level:
    org.hibernate.SQL: debug


server:
  port: 8080
  tomcat:
    additional-tld-skip-patterns:
      - oraclepki.jar
      - osdt_core.jar
      - osdt_cert.jar

  # yaml/yml 파일 - Thymeleaf 설정
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

